version: "3.9"

services:
  supchat-mobile:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supchat-mobile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_USE_DEV_SERVER=true
    tty: true
    stdin_open: true
    command: npx expo start --host lan