version: "3.9"

services:
  supchat-mobile:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supchat-mobile
    ports:
      - "19000:19000"   # Expo Dev Tools / Web Preview
      - "19001:19001"   # React Native Debugger
      - "19002:19002"   # Expo Go connection
      - "8081:8081"     # Metro Bundler
    volumes:
      - .:/app          # Montage pour le développement en live
      - /app/node_modules  # Évite les conflits node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_USE_DEV_SERVER=true
    tty: true           # Permet l'affichage du QR code dans le terminal
    stdin_open: true    # Permet l'interaction avec le terminal
    command: npx expo start --host lan